# Generated by Django 2.2.1 on 2019-05-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='用户名', max_length=255)),
                ('change_points', models.IntegerField()),
                ('tips', models.CharField(help_text='积分加减备注', max_length=255)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='用户名', max_length=255)),
                ('goods', models.CharField(help_text='消费商品', max_length=255)),
                ('goods_id', models.IntegerField(help_text='消费商品ID')),
                ('change_points', models.IntegerField()),
                ('tips', models.CharField(help_text='积分加减备注', max_length=255)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('total_points', models.IntegerField()),
                ('current_points', models.IntegerField(help_text='当前积分')),
                ('level', models.IntegerField(default=1, help_text='会员等级')),
            ],
        ),
    ]
