# Generated by Django 2.2.1 on 2019-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
