# Generated by Django 2.2.1 on 2019-05-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20190514_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='current_points',
        ),
        migrations.RemoveField(
            model_name='points',
            name='level',
        ),
        migrations.RemoveField(
            model_name='points',
            name='total_points',
        ),
        migrations.AddField(
            model_name='points',
            name='all_water',
            field=models.IntegerField(default=0, help_text='当前总流水'),
        ),
        migrations.AddField(
            model_name='points',
            name='month_water',
            field=models.IntegerField(default=0, help_text='当月总流水'),
        ),
    ]
