# Generated by Django 2.2.1 on 2019-05-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20190516_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_to_point', models.IntegerField(help_text='流水积分兑换比例')),
                ('discount_one_Percent', models.FloatField(help_text='1级会员折扣比例')),
                ('discount_one_water', models.IntegerField(help_text='1级会员流水需求')),
                ('discount_two_Percent', models.FloatField(help_text='2级会员折扣比例')),
                ('discount_two_water', models.IntegerField(help_text='2级会员流水需求')),
                ('discount_three_Percent', models.FloatField(help_text='3级会员折扣比例')),
                ('discount_three_water', models.IntegerField(help_text='3级会员流水需求')),
                ('discount_four_Percent', models.FloatField(help_text='4级会员折扣比例')),
                ('discount_four_water', models.IntegerField(help_text='4级会员流水需求')),
                ('discount_five_Percent', models.FloatField(help_text='5级会员折扣比例')),
                ('discount_five_water', models.IntegerField(help_text='5级会员流水需求')),
                ('discount_six_Percent', models.FloatField(help_text='6级会员折扣比例')),
                ('discount_six_water', models.IntegerField(help_text='6级会员流水需求')),
                ('discount_seven_Percent', models.FloatField(help_text='7级会员折扣比例')),
                ('discount_seven_water', models.IntegerField(help_text='7级会员流水需求')),
                ('discount_eight_Percent', models.FloatField(help_text='8级会员折扣比例')),
                ('discount_eight_water', models.IntegerField(help_text='8级会员流水需求')),
            ],
        ),
    ]
