# Generated by Django 2.2.1 on 2019-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_pointconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointconfig',
            name='config_name',
            field=models.CharField(default='默认配置1', max_length=255),
        ),
    ]
