# Generated by Django 2.2.1 on 2019-05-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_pointconfig_config_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointconfig',
            name='auto_flush',
            field=models.CharField(default='2019-01-01', help_text='积分计算起始日期，自动更新1天一次，可联系我手动更新', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointconfig',
            name='config_name',
            field=models.CharField(default='默认配置1', help_text='配置名称', max_length=255),
        ),
    ]
