# Generated by Django 2.2.1 on 2019-06-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20190608_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='half_year_capital_flow',
            field=models.IntegerField(default=0, help_text='半年总流水'),
        ),
        migrations.AlterField(
            model_name='points',
            name='one_year_capital_flow',
            field=models.IntegerField(default=0, help_text='一年总流水'),
        ),
    ]
