# Generated by Django 2.2.1 on 2019-07-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_auto_20190612_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointconfig',
            name='discount_eight_Percent',
        ),
        migrations.RemoveField(
            model_name='pointconfig',
            name='discount_eight_water',
        ),
        migrations.RemoveField(
            model_name='pointconfig',
            name='discount_seven_Percent',
        ),
        migrations.RemoveField(
            model_name='pointconfig',
            name='discount_seven_water',
        ),
        migrations.RemoveField(
            model_name='pointconfig',
            name='discount_six_Percent',
        ),
        migrations.RemoveField(
            model_name='pointconfig',
            name='discount_six_water',
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_five_slot_machine',
            field=models.IntegerField(default=0, help_text='老虎机流水需求'),
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_four_slot_machine',
            field=models.IntegerField(default=0, help_text='老虎机流水需求'),
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_one_slot_machine',
            field=models.IntegerField(default=0, help_text='老虎机流水需求'),
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_special_Percent',
            field=models.FloatField(default=0.82, help_text='特邀会员折扣比例'),
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_special_slot_machine',
            field=models.IntegerField(default=0, help_text='老虎机流水需求'),
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_special_water',
            field=models.IntegerField(default=0, help_text='特邀会员流水需求'),
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_three_slot_machine',
            field=models.IntegerField(default=0, help_text='老虎机流水需求'),
        ),
        migrations.AddField(
            model_name='pointconfig',
            name='discount_two_slot_machine',
            field=models.IntegerField(default=0, help_text='老虎机流水需求'),
        ),
        migrations.AddField(
            model_name='points',
            name='half_year_lottery',
            field=models.FloatField(default=0, help_text='半年彩票流水'),
        ),
        migrations.AddField(
            model_name='points',
            name='month_lottery',
            field=models.FloatField(default=0, help_text='一月彩票流水'),
        ),
        migrations.AddField(
            model_name='points',
            name='one_year_lottery',
            field=models.FloatField(default=0, help_text='一年彩票流水'),
        ),
        migrations.AddField(
            model_name='points',
            name='user_level',
            field=models.IntegerField(default=0, help_text='VIP等级'),
        ),
        migrations.AlterField(
            model_name='points',
            name='half_year_capital_flow',
            field=models.FloatField(default=0, help_text='半年总流水'),
        ),
        migrations.AlterField(
            model_name='points',
            name='one_month_capital_flow',
            field=models.FloatField(default=0, help_text='当月总流水'),
        ),
        migrations.AlterField(
            model_name='points',
            name='one_year_capital_flow',
            field=models.FloatField(default=0, help_text='一年总流水'),
        ),
    ]
