# Generated by Django 2.2.1 on 2019-08-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_auto_20190707_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
