# Generated by Django 2.2.1 on 2019-06-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='用户名', max_length=255)),
            ],
            options={
                'db_table': 'vip_list',
            },
        ),
    ]
