# Generated by Django 2.2.1 on 2019-07-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, help_text='游戏账号', max_length=255)),
                ('user_name', models.CharField(help_text='姓名', max_length=255)),
                ('user_level', models.CharField(blank=True, help_text='官网VIP层级别', max_length=255)),
                ('shop_level', models.IntegerField(default=0, help_text='积分商城VIP')),
                ('level_up', models.IntegerField(default=0, help_text='升级礼金兑换记录')),
                ('flag_level', models.BooleanField(default=0, help_text='升级标识')),
                ('flag_money', models.BooleanField(default=0, help_text='首次标识')),
                ('change_time', models.DateField(auto_now=True)),
                ('current_level_up_money', models.IntegerField(default=0, help_text='当月晋级礼金')),
            ],
            options={
                'db_table': 'vip_list',
            },
        ),
        migrations.CreateModel(
            name='VipSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_valid', models.IntegerField(help_text='VIP客户积分有效期限 单位月')),
                ('common_valid', models.IntegerField(help_text='普通客户积分有效期限 单位月')),
                ('level_up_one', models.IntegerField(default=58, help_text='黄金会员晋级礼金')),
                ('level_up_two', models.IntegerField(default=188, help_text='铂金会员晋级礼金')),
                ('level_up_three', models.IntegerField(default=588, help_text='钻石会员晋级礼金')),
                ('level_up_four', models.IntegerField(default=888, help_text='至尊会员晋级礼金')),
                ('level_up_five', models.IntegerField(default=1888, help_text='王者会员晋级礼金')),
                ('level_up_six', models.IntegerField(default=2888, help_text='特邀会员晋级礼金')),
                ('update_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'vip_setting',
            },
        ),
    ]
