# Generated by Django 2.2.1 on 2019-06-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viplist', '0002_auto_20190608_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viplist',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vipsetting',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
