# Generated by Django 2.2.1 on 2019-06-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viplist', '0003_auto_20190608_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viplist',
            old_name='update_time',
            new_name='change_time',
        ),
    ]
