# Generated by Django 2.2.1 on 2019-07-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(default='Thor', max_length=255)),
                ('capital_flow', models.FloatField(default=0.0, help_text='有效总投注')),
                ('capital_return', models.FloatField(default=0.0, help_text='优惠金小计')),
                ('sports', models.FloatField(default=0.0, help_text='体育赛事')),
                ('table', models.FloatField(default=0.0, help_text='视讯直播')),
                ('slot_machine', models.FloatField(default=0.0, help_text='老虎机')),
                ('lottery', models.FloatField(default=0.0, help_text='彩票')),
                ('fishing_machine', models.FloatField(default=0.0, help_text='捕鱼机')),
                ('poker', models.FloatField(default=0.0, help_text='棋牌')),
                ('update', models.DateField(auto_now=True)),
                ('date', models.DateField(default='2016-06-01')),
            ],
        ),
        migrations.CreateModel(
            name='HalfYearDataStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(default='Thor', max_length=255)),
                ('capital_flow', models.FloatField(default=0.0, help_text='有效总投注')),
                ('capital_return', models.FloatField(default=0.0, help_text='优惠金小计')),
                ('sports', models.FloatField(default=0.0, help_text='体育赛事')),
                ('table', models.FloatField(default=0.0, help_text='视讯直播')),
                ('slot_machine', models.FloatField(default=0.0, help_text='老虎机')),
                ('lottery', models.FloatField(default=0.0, help_text='彩票')),
                ('fishing_machine', models.FloatField(default=0.0, help_text='捕鱼机')),
                ('poker', models.FloatField(default=0.0, help_text='棋牌')),
            ],
        ),
        migrations.CreateModel(
            name='MonthDataStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(default='Thor', max_length=255)),
                ('capital_flow', models.FloatField(default=0.0, help_text='有效总投注')),
                ('capital_return', models.FloatField(default=0.0, help_text='优惠金小计')),
                ('sports', models.FloatField(default=0.0, help_text='体育赛事')),
                ('table', models.FloatField(default=0.0, help_text='视讯直播')),
                ('slot_machine', models.FloatField(default=0.0, help_text='老虎机')),
                ('lottery', models.FloatField(default=0.0, help_text='彩票')),
                ('fishing_machine', models.FloatField(default=0.0, help_text='捕鱼机')),
                ('poker', models.FloatField(default=0.0, help_text='棋牌')),
            ],
        ),
        migrations.CreateModel(
            name='OneYearDataStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(default='Thor', max_length=255)),
                ('capital_flow', models.FloatField(default=0.0, help_text='有效总投注')),
                ('capital_return', models.FloatField(default=0.0, help_text='优惠金小计')),
                ('sports', models.FloatField(default=0.0, help_text='体育赛事')),
                ('table', models.FloatField(default=0.0, help_text='视讯直播')),
                ('slot_machine', models.FloatField(default=0.0, help_text='老虎机')),
                ('lottery', models.FloatField(default=0.0, help_text='彩票')),
                ('fishing_machine', models.FloatField(default=0.0, help_text='捕鱼机')),
                ('poker', models.FloatField(default=0.0, help_text='棋牌')),
            ],
        ),
    ]
