# Generated by Django 2.2.1 on 2019-06-20 11:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('mulu', '0002_goodssortpage_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BargainsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(help_text='发布日期', verbose_name='Post date')),
                ('description', models.CharField(help_text='商品描述', max_length=250)),
                ('points', models.IntegerField(help_text='折扣价')),
                ('discount', models.FloatField(help_text='折扣比例')),
                ('introduce', wagtail.core.fields.RichTextField(blank=True, help_text='商品详细介绍')),
                ('image', models.ForeignKey(blank=True, help_text='商品展示图片', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
