# Generated by Django 2.2.1 on 2019-08-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mulu', '0004_limitbargainspage_limitbargainssortpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitbargainspage',
            old_name='deposit',
            new_name='capital',
        ),
    ]
