# Generated by Django 2.2.3 on 2019-08-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_cookies', models.TextField(help_text='登录信息配置，详情问赵四')),
                ('set_first_time', models.CharField(help_text='第一次活动开始时间', max_length=255)),
                ('set_second_time', models.CharField(help_text='第二次活动开始时间', max_length=255)),
                ('set_third_time', models.CharField(help_text='第三次活动开始时间', max_length=255)),
            ],
        ),
    ]
