# Generated by Django 2.2.3 on 2019-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_promotionsetting_check_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionsetting',
            name='check_cookie',
        ),
    ]
