# Generated by Django 2.2.1 on 2019-05-17 03:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yiwen', '0003_auto_20190517_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=wagtail.core.fields.StreamField([('des1', wagtail.core.blocks.CharBlock(classname='full title')), ('des2', wagtail.core.blocks.CharBlock(classname='full title'))]),
        ),
    ]
