# Generated by Django 2.2.1 on 2019-05-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yiwen', '0004_auto_20190517_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
