# Generated by Django 2.2.1 on 2019-05-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('goods', models.CharField(max_length=255)),
                ('goods_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('wechart', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('tips', models.CharField(help_text='备注', max_length=255)),
                ('cost', models.IntegerField(help_text='消费积分')),
                ('status', models.CharField(choices=[('0', '待确认'), ('1', '待发货'), ('2', '配送中'), ('3', '已送达')], default='0', max_length=255)),
                ('update_time', models.TimeField(auto_now=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
