# Generated by Django 2.2.1 on 2019-05-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
