# Generated by Django 2.2.1 on 2019-05-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('orders', '0003_auto_20190516_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
