# Generated by Django 2.2.1 on 2019-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=1, help_text='折扣比例'),
        ),
        migrations.AddField(
            model_name='orders',
            name='real_cost',
            field=models.IntegerField(default=0, help_text='商品需要积分'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cost',
            field=models.IntegerField(help_text='折扣价'),
        ),
    ]
