# Generated by Django 2.2.1 on 2019-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190517_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(help_text='折扣比例'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='real_cost',
            field=models.IntegerField(help_text='商品需要积分'),
        ),
    ]
