# Generated by Django 2.2.1 on 2019-05-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190517_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.FloatField(help_text='折扣比例'),
        ),
    ]
