# Generated by Django 2.2.1 on 2019-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190612_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(help_text='收货地址', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(help_text='邮箱地址', max_length=254),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(help_text='电话号码'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('0', '待确认'), ('1', '待发货'), ('2', '配送中'), ('3', '已送达'), ('4', '已取消'), ('5', '不符合')], default='0', help_text='订单状态', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='take_name',
            field=models.CharField(help_text='取货姓名', max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wechart',
            field=models.CharField(help_text='微信号码', max_length=255),
        ),
    ]
