# Generated by Django 2.2.1 on 2019-08-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190707_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
